### ISSUE TITLE
MISSING str_literal

### ISSUE THREAD

**Issue by sogaiu** [GrayJack/tree-sitter-janet#2]
The following yields a `MISSING str_literal` here:
```
{:a/b 1}
```
This is with fab96d5ef55d2c4bd297f4fde1dbc2861d6f88b9

**Comment by GrayJack** [comment]
I think it's solved in the last commit (1cdd3770251ae4f5457d64d06f3a7b0a73db72a9)

@sogaiu, can you give a test just as sanity check and a second confirmation?

**Comment by sogaiu** [comment]
Looks good in 1cdd3770251ae4f5457d64d06f3a7b0a73db72a9 :+1:

**Comment by GrayJack** [comment]
Thanks!!
